### ISSUE TITLE
There are lots of errors when open via Unity? 

### ISSUE THREAD

**Issue by v23v** [FirstGearGames/FishNet-Examples#1]
This examples can not run via unity, because there are lots of errors. Is there lack of some scripts or dll?

**Comment by AugusDogus** [comment]
> This examples can not run via unity, because there are lots of errors. Is there lack of some scripts or dll?

Saw likely the same errors you were seeing upon starting the project in Unity 2020.3.32f1 LTS, however every error was resolved after installing the required dependencies noted in the project's readme.
