### ISSUE TITLE
Two Errors after opening project

### ISSUE THREAD

**Issue by clankill3r** [FirstGearGames/FishNet-Examples#3]
After importing the required packages I'm left with two errors:

First one:

> Assets\Walkthrough\Scripts\PlayerNameTracker.cs(51,37): error CS0103: The name 'RemoteConnectionStates' does not exist in the current context

When I do a text search for `RemoteConnectionStates` then I never find it, not even inside FishNet.

Second one:

> Assets\API\Remote Calls\Scripts\RemoteCalls.cs(40,95): error CS0117: 'NetworkBehaviour' does not contain a definition for 'OwnerIsActive'

When I do a search in the FishNet code, I  find `OwnerIsActive` only once, in a line that is commented.

Some help would be welcome.

**Comment by clankill3r** [comment]
Ok, I found it mentioned in the break solutions here (good job for having that page).

https://fish-networking.gitbook.io/docs/manual/general/changelog/break-solutions

```
Break: Several enums are being changed from plural to singular. Those changed will be SceneScopeTypes, ServerUnloadModes, LocalConnectionStates, RemoteConnectionStates.

Resolve: remove plural (s) from each enum reference.
```

```
Break: obsolete NetworkBehaviour/NetworkObject.OwnerIsActive

Resolve: NetworkBehaviour/NetworkObject.Owner.IsActive
```

In case the first one is not clear for people, change `RemoteConnectionStates` to `RemoteConnectionState`.
(I don't know what a plural is...)

**Comment by FirstGearGames** [comment]
It looks like this git became forgotten about during the major update. I'll try to get these fixes in soon, as you discovered it's not much work.
